In [9]:
import torch

In [10]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [11]:
torch.manual_seed(7)

features = torch.randn((1, 5))

weights = torch.randn_like(features)

bais = torch.randn((1, 1))

In [17]:
y = activation(torch.sum(torch.mm(features, weights.reshape(5, 1))) + bais)

In [18]:
y

tensor([[0.1595]])

In [26]:
torch.manual_seed(7)

features = torch.randn((1, 3))

n_input = features.shape[1]
n_output = 1
n_hidden = 2

W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [33]:
H = activation(torch.matmul(features, W1) + B1)
O = activation(torch.matmul(H, W2) + B2)
print(O)

tensor([[0.3171]])


In [34]:
import numpy as np

In [36]:
a = np.random.randn(4, 3)
a

array([[-0.62560728,  0.09120747, -0.52415468],
       [ 0.81386895,  0.25588438,  0.44074289],
       [-0.52962712, -1.83233887,  1.93342384],
       [ 0.3648102 , -1.02182792, -2.71718657]])

In [39]:
b = torch.from_numpy(a)
b

tensor([[-0.6256,  0.0912, -0.5242],
        [ 0.8139,  0.2559,  0.4407],
        [-0.5296, -1.8323,  1.9334],
        [ 0.3648, -1.0218, -2.7172]], dtype=torch.float64)

In [40]:
b.numpy()

array([[-0.62560728,  0.09120747, -0.52415468],
       [ 0.81386895,  0.25588438,  0.44074289],
       [-0.52962712, -1.83233887,  1.93342384],
       [ 0.3648102 , -1.02182792, -2.71718657]])

In [41]:
b.mul_(2)

tensor([[-1.2512,  0.1824, -1.0483],
        [ 1.6277,  0.5118,  0.8815],
        [-1.0593, -3.6647,  3.8668],
        [ 0.7296, -2.0437, -5.4344]], dtype=torch.float64)

In [42]:
a

array([[-1.25121456,  0.18241494, -1.04830936],
       [ 1.6277379 ,  0.51176875,  0.88148578],
       [-1.05925424, -3.66467774,  3.86684768],
       [ 0.72962041, -2.04365583, -5.43437314]])

In [43]:
# Even here referencing exists